### ISSUE TITLE
What should pySA do ?

### ISSUE THREAD

**Issue by srisankethu** [pySA-dev/pySA#2]
I think pySA should take in the inputs about a structural member and draw  shear force and bending moment diagrams. We might need to use graphs for plotting the diagrams. Lets check for any existing tool which helps us draw graphs.So using pyplot might help us extend our knowledge in python. Since pySA, is an educational tool, we need to draw simple plots for SFD and BMD, it seemed very easy in pyplot. We will check in other tools too! What do you think @saurabhiiit ? The project might not take much time ! 1 month is a lot a time to give in i guess ! But I hope we get selected for GSoC :+1:

**Comment by saurabhiiit** [comment]
I feel that pyplot is best option for us in the 2D, and  later for 3D  of the project we could use pythonocc or open cascade.
True we can do this in 1 month and I also hope we get selected.

**Comment by srisankethu** [comment]
We should plan out what is the purpose of pySA and our design should be based on its purpose. I want pySA to be an educational tool rather than a commercial product( it could be copyrighted and sold if we want to!) whose focus should be on drawing SFD and BMD diagrams and educating the method of drawing and related calculations. The explanation part will be taken from pre-written explanation texts. So this is a small project! Please share here if you have anything in mind @saurabhiiit .

**Comment by saurabhiiit** [comment]
Nice Idea, We could do structural analysis as one project and Design of concrete structures as another project and later we can integrate these as a single project. This  process make us to integerate more and more  sub projects if later made

**Comment by srisankethu** [comment]
:+1:  We could do that but the code written should be *simply awesome* and integrable. What we have learnt in SSAD course might be of help to make a perfect design model. About the integration part, we need to stick to a tool else we need wrappers and everything will be fuzzy. 

Ideas for the far future:
1. Code linter
2. Organisation website( github pages)

**Comment by srisankethu** [comment]
Ok! So is it decided than pySA is going to be an educational tool?

**Comment by srisankethu** [comment]
Further discussion continues here -> https://github.com/pySA-dev/pySA/issues/3
