### ISSUE TITLE
Do we need a organisation website right now?

### ISSUE THREAD

**Issue by srisankethu** [pySA-dev/pySA#4]
Thinking to build an organisation website after we are finalised with the designing. what do u think guys?

**Comment by saurabhiiit** [comment]
If we first make our back-end working then after we can think of the front-end, I think frontend will not be that problematic than working of  backend

**Comment by srisankethu** [comment]
@saurabhiiit Why are you bringing back-end and front-end development into this? We are not building pySA as a web assessable tool( we may do that too :+1: ). Back-end and front-end development are related  to web-development.

**Comment by saurabhiiit** [comment]
You get right...
I thought that implementing everything at time could create problem of integeration as Issues which will be there would be from both side,
but yeah we can make that its a good idea :+1:

**Comment by srisankethu** [comment]
I think if we have done resonsable no of good projects/work, it is need. Let the time decide :+1:
